name: Deploy Static HTML to Azure Web App - task2-simple-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Needed for Azure login with OIDC
      contents: read   # Needed to fetch repository content

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip static site content
        run: zip release.zip . -r

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3949053AB8D34A70821D8A44C58796C8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_24D13D90A458479C81EDF590FFF256E0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_58675065B06A48338010D1566732C374 }}

      - name: Deploy static HTML to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'task2-simple-webapp'
          slot-name: 'Production'
          package: release.zip
