# Docs: https://github.com/Azure/webapps-deploy

name: Deploy Static HTML to Azure Web App - task2-simple-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip static HTML files
        run: zip -r release.zip . -x '*.git*' '*.github*'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'task2-simple-webapp'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C55EC29F366C47FBBB1270871EEF25DB }}
